### ISSUE TITLE
missing classes.txt

### ISSUE THREAD

**Issue by Forsakenrox** [php-opencv/php-opencv-examples#18]
I want make just one question - how did you get file classes.txt ? 
Im try to find any kind of something like this in internet and other pretrained models, but im fail in it. Can you explain how to extract this classes from pretrained model downloaded from internet or extract them from pbtxt or pb file ?

**Comment by morozovsk** [comment]
Are you about ssd_mobilenet_v1_**coco**/classes.txt ?
https://www.google.com/search?q=coco+classes
You couldn't extract classes from model because model contains only numbers of classes.
Almost links to sources you can find on page https://github.com/php-opencv/php-opencv-examples/tree/master/models

**Comment by Forsakenrox** [comment]
In this case, without this file, I will not be able to mark the found objects in the image by their names. Most models on the Internet only come with a .pb and .pbtxt file. It’s sad. Anyway - thanks for the answer. It seems to me if you are still interested in doing this project - it would be nice to write a tutorial about training models and their subsequent use in this project
